# Application Info
info:
  name: springbootapp-service
  description: SpringBoot
  version: 1.0-SNAPSHOT

server:
  port: 8080
  context-path: /springbootapp-service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    schema: sda

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        default_schema: sda
        hbm2ddl.auto: update
        hibernate.show_sql: true
        hibernate.format_sql: true

logging:
  level:
    matchingstore: 'INFO'